### ISSUE TITLE
Question: ETA on Release with Validation

### ISSUE THREAD

**Issue by HerbBoy** [mitre/redhat-enterprise-linux-9-stig-baseline#38]
Hi,

Just was wondering if the team has a expected release date for when validation logic will be written into the controls?

**Comment by aaronlippold** [comment]
The ongoing work is in branch v1r2

We guess it will be about another two weeks or so.

**Comment by wdower** [comment]
@HerbBoy -- we've released v1r2 of the validation profile. All controls now actually have validation logic.
