### ISSUE TITLE
Add conf file checks to kernel module controls

### ISSUE THREAD

**Issue by wdower** [mitre/redhat-enterprise-linux-9-stig-baseline#40]
Right now the InSpec `kernel module` resource gives info on the actively loaded kernel modules but nothing on the contents of the conf files in /etc/modprobe.conf and /etc/modprobe.d/*. The profile needs an explicit check for those.

**Comment by kemley76** [comment]
It appears that the InSpec `kernel module` resource uses the [`modprobe`](https://www.man7.org/linux/man-pages/man8/modprobe.8.html) command by running `modprobe --showconfig` to get the contents of the configuration files. See resource code [here](https://github.com/inspec/inspec/blob/main/lib/inspec/resources/kernel_module.rb#L59-L84). This issue can probably be safely closed.
