### ISSUE TITLE
mailx (rhel8) Needs to be 's-nail' (rhel9) I believe

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#49]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/inspec.yml#L748

Needs to be 's-nail' based off of SV-257842

**Comment by karikarshivani** [comment]
The issue reporter confirmed that this issue no longer exists.
