### ISSUE TITLE
SV-258242 not applicable if BIND not installed

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#50]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/main/controls/SV-258242.rb

Look at the STIG again.
https://www.stigviewer.com/stig/red_hat_enterprise_linux_9/2023-09-13/finding/V-258242

`Note: If the "bind" package is not installed, this requirement is Not Applicable.`

**Comment by jrmetzger** [comment]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-258242.rb#L49

Line exists in file, but reporting it is not

        /* https://fedoraproject.org/wiki/Changes/CryptoPolicy */
        include "/etc/crypto-policies/back-ends/bind.config";

**Comment by karikarshivani** [comment]
The issue reporter confirmed that this issue no longer exists.
