### ISSUE TITLE
Meant to put net.ipv4.icmp_ignore_bogus_error_responses

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#51]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blame/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-257967.rb#L46

net.ipv4.icmp_ignore_bogus_error_response**s** not net.ipv4.icmp_ignore_bogus_error_response

**Comment by karikarshivani** [comment]
The issue reporter confirmed that this issue no longer exists.
