### ISSUE TITLE
Audit conflict: SV-230489: RHEL 8 must not have the sendmail package installed.

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#52]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-258157.rb#L30

I know STIG wants this to be 'email' however when running `systemctl status auditctl` an error: 

`Email option is specified but /usr/lib/sendmail doesn't seem executable.`

Since sendmail is removed. Option to use another method, but STIG prefers email. Option to use another method? Or another mail binary for rhel9.

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
