### ISSUE TITLE
Deprecated option UsePrivilegeSeparation

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#53]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-258010.rb#L40

`systemctl status sshd` -> Deprecated option UsePrivilegeSeparation

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
