### ISSUE TITLE
SV-257819: Update redhat repo Auxiliary key 3 inspec.yml from description

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#54]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/inspec.yml#L762C1-L763C1

7E46 2425 8C40 6535 D56D  6F13 5054 E4A4 5A63 40B3

States in description, but not copied over to inspec.yml

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
