### ISSUE TITLE
Double File Reference (found elsewhere too)

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#55]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-257790.rb#L32

Double file?

Should just be the input('file_name')

**Comment by jrmetzger** [comment]
SV-257791

**Comment by jrmetzger** [comment]
SV-257787

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
