### ISSUE TITLE
Already set config in file, but profile not picking up

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#57]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-258116.rb#L33

crypt_style = sha512

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
