### ISSUE TITLE
Duplicate controls Encrypted MACs, different expected

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#58]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/main/controls/SV-257990.rb

https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/main/controls/SV-257991.rb 

Do we want both MACs? or looking for ONLY those MACs?

**Comment by jrmetzger** [comment]
Also is openssh not opensshserver

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
