### ISSUE TITLE
Dup control, should be system-auth

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-9-stig-baseline#60]
https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline/blob/1dee0651ae4621c41dfa689133f7c4bb3ae72e81/controls/SV-258100.rb#L39

system-auth not password-auth

**Comment by karikarshivani** [comment]
The issue reporter confirmed that the issue no longer exists.
